# Mozilla User Preferences

/* Do not edit this file.
 *
 * If you make changes to this file while the application is running,
 * the changes will be overwritten when the application exits.
 *
 * To make a manual change to preferences, you can visit the URL about:config
 */

user_pref("app.update.lastUpdateTime.addon-background-update-timer", 1523425877);
user_pref("app.update.lastUpdateTime.background-update-timer", 1523425757);
user_pref("app.update.lastUpdateTime.blocklist-background-update-timer", 1523425997);
user_pref("app.update.lastUpdateTime.browser-cleanup-thumbnails", 1523426117);
user_pref("app.update.lastUpdateTime.search-engine-update-timer", 1452509925);
user_pref("browser.bookmarks.restore_default_bookmarks", false);
user_pref("browser.cache.disk.capacity", 358400);
user_pref("browser.cache.disk.smart_size.first_run", false);
user_pref("browser.cache.disk.smart_size.use_old_max", false);
user_pref("browser.cache.disk.smart_size_cached_value", 358400);
user_pref("browser.download.panel.firstSessionCompleted", true);
user_pref("browser.migration.version", 13);
user_pref("browser.newtabpage.storageVersion", 1);
user_pref("browser.pagethumbnails.storage_version", 3);
user_pref("browser.places.smartBookmarksVersion", 4);
user_pref("browser.preferences.advanced.selectedTabIndex", 0);
user_pref("browser.rights.3.shown", true);
user_pref("browser.slowStartup.averageTime", 2081);
user_pref("browser.slowStartup.samples", 2);
user_pref("browser.startup.homepage", "file:///home/ws");
user_pref("browser.startup.homepage_override.buildID", "20131029083213");
user_pref("browser.startup.homepage_override.mstone", "24.1.0");
user_pref("datareporting.healthreport.nextDataSubmissionTime", "1452596204730");
user_pref("datareporting.healthreport.service.firstRun", true);
user_pref("datareporting.policy.dataSubmissionPolicyNotifiedTime", "1523425698865");
user_pref("datareporting.policy.firstRunTime", "1452509804730");
user_pref("datareporting.sessions.current.activeTicks", 23);
user_pref("datareporting.sessions.current.firstPaint", 1033);
user_pref("datareporting.sessions.current.main", 352);
user_pref("datareporting.sessions.current.sessionRestored", 1103);
user_pref("datareporting.sessions.current.startTime", "1523425635952");
user_pref("datareporting.sessions.current.totalTime", 1473);
user_pref("datareporting.sessions.currentIndex", 1);
user_pref("datareporting.sessions.prunedIndex", 0);
user_pref("extensions.blocklist.pingCountTotal", 2);
user_pref("extensions.blocklist.pingCountVersion", 2);
user_pref("extensions.bootstrappedAddons", "{}");
user_pref("extensions.databaseSchema", 14);
user_pref("extensions.enabledAddons", "%7B972ce4c6-7e08-4474-a285-3208198ce6fd%7D:24.1.0");
user_pref("extensions.installCache", "[{\"name\":\"app-global\",\"addons\":{\"{972ce4c6-7e08-4474-a285-3208198ce6fd}\":{\"descriptor\":\"/usr/lib64/firefox-24.1.0/browser/extensions/{972ce4c6-7e08-4474-a285-3208198ce6fd}\",\"mtime\":1383055466000,\"rdfTime\":1383055446000}}}]");
user_pref("extensions.lastAppVersion", "24.1.0");
user_pref("extensions.lastPlatformVersion", "24.1.0");
user_pref("extensions.pendingOperations", false);
user_pref("extensions.shownSelectionUI", true);
user_pref("gecko.buildID", "20131029083213");
user_pref("gecko.mstone", "24.1.0");
user_pref("idle.lastDailyNotification", 1523427285);
user_pref("intl.charsetmenu.browser.cache", "KOI8-R, windows-1251, UTF-8");
user_pref("network.cookie.prefsMigrated", true);
user_pref("pdfjs.migrationVersion", 1);
user_pref("pdfjs.previousHandler.alwaysAskBeforeHandling", true);
user_pref("pdfjs.previousHandler.preferredAction", 4);
user_pref("places.history.expiration.transient_current_max_pages", 104858);
user_pref("plugin.disable_full_page_plugin_for_types", "application/pdf");
user_pref("plugin.importedState", true);
user_pref("pref.browser.homepage.disable_button.current_page", false);
user_pref("privacy.sanitize.migrateFx3Prefs", true);
user_pref("services.sync.clients.lastSync", "0");
user_pref("services.sync.clients.lastSyncLocal", "0");
user_pref("services.sync.globalScore", 0);
user_pref("services.sync.migrated", true);
user_pref("services.sync.nextSync", 0);
user_pref("services.sync.tabs.lastSync", "0");
user_pref("services.sync.tabs.lastSyncLocal", "0");
user_pref("storage.vacuum.last.index", 0);
user_pref("toolkit.startup.last_success", 1523425636);
user_pref("toolkit.telemetry.previousBuildID", "20131029083213");
user_pref("urlclassifier.keyupdatetime.https://sb-ssl.google.com/safebrowsing/newkey", 1526017639);
user_pref("xpinstall.whitelist.add", "");
user_pref("xpinstall.whitelist.add.180", "");
user_pref("xpinstall.whitelist.add.36", "");
