# Mozilla User Preferences

/* Do not edit this file.
 *
 * If you make changes to this file while the application is running,
 * the changes will be overwritten when the application exits.
 *
 * To make a manual change to preferences, you can visit the URL about:config
 */

user_pref("app.update.lastUpdateTime.addon-background-update-timer", 1452509730);
user_pref("app.update.lastUpdateTime.background-update-timer", 0);
user_pref("app.update.lastUpdateTime.blocklist-background-update-timer", 0);
user_pref("app.update.lastUpdateTime.search-engine-update-timer", 1452509610);
user_pref("browser.bookmarks.restore_default_bookmarks", false);
user_pref("browser.cache.disk.capacity", 358400);
user_pref("browser.cache.disk.smart_size.first_run", false);
user_pref("browser.cache.disk.smart_size.use_old_max", false);
user_pref("browser.cache.disk.smart_size_cached_value", 358400);
user_pref("browser.history.last_page_visited", "http://bigor.bmstu.ru/");
user_pref("browser.places.smartBookmarksVersion", 4);
user_pref("browser.rights.1.shown", true);
user_pref("browser.startup.homepage", "file:///home/ws");
user_pref("browser.startup.homepage_override.mstone", "rv:24.0");
user_pref("extensions.blocklist.pingCountVersion", 0);
user_pref("extensions.bootstrappedAddons", "{}");
user_pref("extensions.databaseSchema", 14);
user_pref("extensions.enabledAddons", "%7B59c81df5-4b7a-477b-912d-4e0fdf64e5f2%7D:0.9.90,%7Bf13b157f-b174-47e7-a34d-4815ddfdfeb8%7D:0.9.89,inspector%40mozilla.org:2.0.15pre,%7B972ce4c6-7e08-4474-a285-3208198ce6fd%7D:2.21");
user_pref("extensions.installCache", "[{\"name\":\"app-global\",\"addons\":{\"modern@themes.mozilla.org\":{\"descriptor\":\"/usr/lib64/seamonkey-2.21/extensions/modern@themes.mozilla.org.xpi\",\"mtime\":1380404801000},\"{972ce4c6-7e08-4474-a285-3208198ce6fd}\":{\"descriptor\":\"/usr/lib64/seamonkey-2.21/extensions/{972ce4c6-7e08-4474-a285-3208198ce6fd}.xpi\",\"mtime\":1380404801000}}},{\"name\":\"app-profile\",\"addons\":{\"{59c81df5-4b7a-477b-912d-4e0fdf64e5f2}\":{\"descriptor\":\"/home/ws/.mozilla/seamonkey/01n8nk4w.default/extensions/{59c81df5-4b7a-477b-912d-4e0fdf64e5f2}.xpi\",\"mtime\":1452509370000},\"{f13b157f-b174-47e7-a34d-4815ddfdfeb8}\":{\"descriptor\":\"/home/ws/.mozilla/seamonkey/01n8nk4w.default/extensions/{f13b157f-b174-47e7-a34d-4815ddfdfeb8}.xpi\",\"mtime\":1452509370000},\"inspector@mozilla.org\":{\"descriptor\":\"/home/ws/.mozilla/seamonkey/01n8nk4w.default/extensions/inspector@mozilla.org.xpi\",\"mtime\":1452509370000}}}]");
user_pref("extensions.installedDistroAddon.inspector@mozilla.org", true);
user_pref("extensions.installedDistroAddon.{59c81df5-4b7a-477b-912d-4e0fdf64e5f2}", true);
user_pref("extensions.installedDistroAddon.{f13b157f-b174-47e7-a34d-4815ddfdfeb8}", true);
user_pref("extensions.lastAppVersion", "2.21");
user_pref("extensions.lastPlatformVersion", "24.0");
user_pref("extensions.pendingOperations", false);
user_pref("extensions.shownSelectionUI", true);
user_pref("intl.charsetmenu.browser.cache", "windows-1251");
user_pref("network.cookie.prefsMigrated", true);
user_pref("places.history.expiration.transient_current_max_pages", 104858);
user_pref("plugin.importedState", true);
user_pref("privacy.sanitize.didShutdownSanitize", true);
user_pref("toolkit.telemetry.previousBuildID", "20130928161451");
user_pref("urlclassifier.keyupdatetime.https://sb-ssl.google.com/safebrowsing/newkey", 1455101396);
user_pref("xpinstall.whitelist.add", "");
user_pref("xpinstall.whitelist.add.36", "");
